name: Go
on: [push]
jobs:

  build:
    name: Lint, Test, Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:

    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - uses: actions/checkout@v5

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Build
      run: make build

  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: make build-image
