name: Go
on: [push]
jobs:

  build:
    name: Lint, Test, Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:

    - uses: actions/setup-go@v5

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Build
      run: make build
